<?php
$texts = [
    'en' => [
        // --- User Interface Texts ---
        'home' => 'Home',
        'wilayas' => 'Wilayas',
        'attractions' => 'Attractions',
        'map' => 'Interactive Map',
        'search' => 'Search',
        'login' => 'Log In',
        'profile' => 'My Profile',
        'logout' => 'Log out', 
        'slide1_title' => 'The magic of the Algerian desert',
        'slide1_desc'  => "Discover the tranquility of the golden sands and the grandeur of Tassili N'Ajjer",
        'slide2_title' => 'The beauty of the coast',
        'slide2_desc'  => 'Enjoy the enchanting beaches of Annaba and Jijel under the sun',
        'slide3_title' => 'The scent of history and authenticity',
        'slide3_desc'  => 'Wander through the alleys of the ancient Kasbah and discover the story of civilizations',
        'slide4_title' => 'The majestic Djurdjura Mountains',
        'slide4_desc'  => 'Where snow meets green nature in a breathtaking scene',
        'beach' => 'Beach',
        'desert' => 'Desert',
        'nature' => 'Nature',
        'history' => 'Historical & Cultural',
        'all' => 'All',
        'logo_main'     => 'Haws AL-jazair',
        'logo_sub'      => 'ALGERIA',
        'main_title'    => 'Discover the wilayas',
        'all_wilayas'   => 'View all wilayas ',
        'hero_butt'     => 'Start your travel now',
        'explore_btt'   => 'Explore the wilaya',
        'section_tit'   => 'Discover the attractions of Algeria',
        'btn_explore'   => 'Explore the attraction',
        'page_tit'      => 'All Wilayas ',
        'map_title'     => 'Discover your destination from the map',
        'about_wilaya'       => 'About Wilaya',
        'tourist_attractions' => 'Tourist Attractions',
        'best_restaurants'   => 'Best Restaurants',
        'recommended_hotels' => 'Recommended Hotels',
        'restaurant'        => 'Restaurants',
        'hotel'             => 'Hotels',
        'welcome_to'     =>'WELCOME TO',
        'opinions'       =>'Visitor opinions and comments ',
        'publish'    => 'Publish now',
        'explore_thet_attraction'     =>'Explore the attraction',
        'sorry'    =>'Sorry, you must ',
        'add_comment'   =>'To add a comment and see visitor reviews',
        'caree'    => ' Please type something into the search box',
        'back'    => 'Return to main page',
        'try_search'   => 'Try searching for a different state or a different tourist attraction.',
        'excu'   => 'Sorry, we found no results...',
        'det_att'  => 'Attraction details',
        'wilaya'   => 'wilaya',
        'serch_result'   => 'The following results were found in wilayas and Tourist Attractions',
        'result_s'  => 'Search results for:',
        'gallery'   => 'Photo Gallery ',
        'about_att'  => 'About the attraction',
        'exp_now'    => 'Explore now',

        // --- Admin Dashboard Texts ---
        'admin_panel' => 'Control Panel',
        'wilaya_mgmt' => 'Wilaya Management',
        'attraction_mgmt' => 'Attraction Management',
        'restaurant_mgmt' => 'Restaurant Management',
        'hotel_mgmt' => 'Hotel Management',
        'comments' => 'Comments',
        'welcome' => 'welcome',
        'restaurants' => 'Restaurants',
        'hotels' => 'hotels',
        'users' => 'users',
        'quick_actions' => 'Quick actions',
        'add_wilaya' => 'add a new wilaya',
        'add_attraction' => 'add a new attraction',
        'add_restaurant' => 'ad a new Restaurant',
        'add_hotel' => 'add a new hotel',
        'view_site' => 'view site',
        'tourism_mgmt' => 'Tourism Management',

        // --- Wilaya Table Columns (EN) ---
        'col_image' => 'Image',
        'col_name' => 'Wilaya Name',
        'col_coords' => 'Coordinates (Lat/Lng)',
        'col_desc' => 'Description',
        'col_actions' => 'Actions',
        'confirm_delete' => 'Are you sure you want to delete this?',

        'col_att_name' => 'Attraction Name',
        'col_wilaya' => 'Wilaya',

        'col_rest_name' => 'Restaurant Name',

       'col_hotel_name' => 'Hotel Name',

       'update_wilaya_title' => 'Update Wilaya Data',
        'select_wilaya' => 'Select Wilaya',
        'desc_ar' => 'Description (Arabic)',
        'desc_en' => 'Description (English)',
       'upload_img' => 'Upload Image',
        'select_file' => 'Select from Computer',
        'latitude' => 'Latitude',
        'longitude' => 'Longitude',
        'btn_update' => 'Update & Save Data',
        'success_update' => 'Updated Successfully!',

        'add_attraction_title' => 'Add New Attraction',
        'name_ar' => 'Name (Arabic)',
        'name_en' => 'Name (English)',
        'col_category' => 'Category',
        'img_multi_hint' => 'Images (1st is Main Display)',
        'select_multi' => 'Select Multiple Images',
        'btn_save' => 'Save Attraction',
        'success_add' => 'Added Successfully!',
        'main_label' => 'Main',

        'add_restaurant_title' => 'Add New Restaurant',
        'rest_name_en' => 'Restaurant Name (English)',
        'rest_name_ar' => 'Restaurant Name (Arabic)',
        'rest_img' => 'Restaurant Image',
        'click_select_img' => 'Click to Select Photo',
        'btn_save_rest' => 'Save Restaurant',
        'success_add_rest' => 'Restaurant Added Successfully!',

'add_hotel_title' => 'Add New Hotel',
'hotel_name_en' => 'Hotel Name (English)',
'hotel_name_ar' => 'Hotel Name (Arabic)',
'hotel_img' => 'Hotel Image',
'btn_save_hotel' => 'Save Hotel Details',
'success_add_hotel' => 'Hotel Added Successfully!',

'edit_wilaya_header' => 'Edit Wilaya Info',
'wilaya_name_ar_label' => 'Wilaya Name (Arabic)',
'desc_ar_label' => 'Description (Arabic)',
'current_photo_label' => 'Current Photo',
'change_photo_label' => 'Change Photo (Optional)',
'btn_save_all' => 'Save All Changes',

'edit_attraction_header' => 'Edit Attraction Details',
'attraction_name_ar_label' => 'Attraction Name (Arabic)',
'desc_ar_label' => 'Description (Arabic)',
'btn_update_attraction' => 'Update Attraction',

'edit_restaurant_title' => 'Edit Restaurant',
'restaurant_name_ar_label' => 'Restaurant Name (Arabic)',
'btn_save_restaurant' => 'Save Restaurant Changes',

'edit_hotel_title' => 'Edit Hotel',
'hotel_name_ar_label' => 'Hotel Name (Arabic)',
'price_label' => 'Price Per Night (DA)',
'btn_save_hotel' => 'Save Hotel Changes',
'btn_cancel'   => 'Cancel',


'page_tit' => 'Explore Algerian Wilayas',
'exp_now' => 'Explore Now',
'map' => 'Interactive Map',
'create_new_cc' => 'Create a new account',
'sure'     => "?Don't have an account?",
'btn_reset' => 'Reset Changes',
'back_to_mgmt' => 'Back to Management',
'col_lat' => 'Latitude (Lat)',
'col_lng' => 'Longitude (Lng)',
'back_to_mgmt_att' => 'Back to Attractions Management',
'attraction_name_en_label' => 'Attraction Name (EN)',
'desc_en_label' => 'Description (EN)',
'back_to_mgmt_res' => 'Back to Restaurants Management',

'btn_save_restaurant' => 'Update & Save Data',
'restaurant_name_ar_label' => 'Restaurant Name (Arabic)',

'back_to_mgmt_hotel' =>'Back to hotels Management',

'back_to_mgmt_wilaya' => 'Back to Wilayas Management',
'btn_reset' => 'Reset / Undo',

'statistics_overview' => 'Statistics Overview',
'data_distribution' => 'Data Distribution',
'total_comments' => 'Total Comments',

'latest_additions' => 'Latest Additions',
'top_content' => 'Top Content',
'attractions_by_type' => 'Attractions by Type',
'wilayas_stats' => 'Wilayas Statistics',
'museums' => 'Museums',
'parks' => 'Parks',
'beaches' => 'Beaches',
'historical' => 'Historical Sites',

'top_liked' => 'Most Liked',
'completed_wilayas' => 'Completed Wilayas',
'attractions_distribution' => 'Attractions per Wilaya',


'statistics' => 'Site Statistics',
'categories_dist' => 'Attractions by Category',
'wilaya_dist' => 'Attractions per Wilaya',
'historical_cultural' => 'Historical & Cultural',
'nature' => 'Nature',
'desert' => 'Desert',
'beach' => 'Beach',

'top_commented' => 'Top Commented Areas',
'active_wilayas' => 'Most Active Wilayas',
'add_hotel' => 'Add Hotel',
'add_restaurant' => 'Add Restaurant',


'ai_assistant' => 'AI Smart Assistant',
'searching_location' => 'Locating you...',
'nearby_places' => 'Location Found!',
'location_success' => 'We found your location. The map will now guide you to nearby landmarks.',
'location_denied' => 'Please allow location access to enable smart features',


'stats_title' => 'Discover the Spirit of Algeria',
'stats_wilayas' => 'Provinces to explore',
'stats_attractions' => 'Registered landmarks',
'stats_unesco' => 'UNESCO World Heritage sites',


'ai_title' => 'Smart Assistant',
'ai_welcome' => 'Hello 👋 How can I help you discover Algeria?',
'ai_placeholder' => 'Ask something...',
'ai_default_reply' => '✨ I can help you discover beautiful places in Algeria',
'ai_beach_reply' => '🏖️ Best beaches: Oran, Jijel and Bejaia',
'ai_desert_reply' => '🏜️ Discover Djanet, Tamanrasset and the Algerian desert',
'ai_history_reply' => '🏛️ Visit Casbah, Timgad and Roman ruins',
'ai_nature_reply' => '🌲 Algeria has beautiful mountains, forests and waterfalls',

'ai_suggest_title' => 'Suggestions for you:',
'ai_no_result' => 'Sorry, I couldn\'t find specific info. Did you mean another place?',
'ai_more_info' => 'Learn More',



'review_title' => 'Share Your Experience',
'review_subtitle' => 'Your feedback helps us improve tourism in Algeria',
'improve_question' => 'What should we improve?',
'suggest_design' => 'Improve Design',
'suggest_places' => 'Add More Places',
'suggest_ai' => 'Improve AI Assistant',
'suggest_speed' => 'Improve Website Speed',
'suggest_translation' => 'Improve Translation',
'suggest_hotels' => 'Add More Hotels',
'write_suggestion' => 'Write your own suggestion...',
'send_review' => 'Send Review',
'login_to_review' => 'You must login to review the website',
'review_success' => 'Thank you ❤️ Your review has been sent successfully',


'site_ratings' => 'Site Ratings',
'user_suggestions' => 'User Suggestions',
    ],

    'ar' => [
        // --- User Interface Texts ---
        'home' => 'الرئيسية',
        'wilayas' => 'الولايات',
        'attractions' => 'المعالم السياحية',
        'map' => 'الخريطة التفاعلية',
        'search' => 'بحث',
        'login' => 'تسجيل الدخول',
        'profile' => 'ملفي الشخصي',
        'logout' => 'خروج',
        'slide1_title' => 'سحر الصحراء الجزائرية',
        'slide1_desc'  => 'اكتشف هدوء الرمال الذهبية وروعة طاسيلي ناجر',
        'slide2_title' => 'جمال الساحل',
        'slide2_desc'  => 'استمتع بالشواطئ الساحرة في عنابة وجيجل تحت أشعة الشمس',
        'slide3_title' => 'عبق التاريخ والأصالة',
        'slide3_desc'  => 'تجول في أزقة القصبة العتيقة واكتشف تاريخ الحضارات',
        'slide4_title' => 'جبال جرجرة الساحرة',
        'slide4_desc'  => 'حيث يلتقي الثلج بالطبيعة الخضراء في مشهد خلاب',
        'beach' => 'شاطئ',
        'desert' => 'صحراء',
        'nature' => 'طبيعة',
        'history' => 'تاريخي وثقافي',
        'all' => 'الكل',
        'logo_main'     => 'حوس الجزائر', 
        'logo_sub'      => 'الجزائر',
        'main_title'    => 'اكتشف الولايات',
        'all_wilayas'   => 'عرض جميع الولايات',
        'hero_butt'     => 'ابدأ رحلتك الآن',
        'explore_btt'   => 'استكشف الولاية',
        'section_tit'   => 'اكتشف معالم الجزائر السياحية',
        'btn_explore'   => 'استكشف المعلم',
        'page_tit'      => 'جميع الولايات ',
        'map_title'     => 'اكتشف وجهتك من خلال الخريطة',
        'about_wilaya'       => 'عن الولاية',
        'tourist_attractions' => 'المعالم السياحية',
        'best_restaurants'   => 'أفضل المطاعم',
        'recommended_hotels' => 'فنادق مقترحة',
        'restaurant'        => 'مطاعم',
        'hotel'             => 'فنادق',
        'welcome_to'     =>'أهلاً وسهلاً بكم في',
        'opinions'       =>'آراء وتعليقات الزوار',
        'publish'    => 'انشر الآن ',
        'explore_thet_attraction'     =>'استكشف المعلم',
        'sorry'    =>'عذراً، يجب عليك ',
        'add_comment'   =>'لإضافة تعليق والاطلاع على تقييمات الزوار',
        'caree'    => ' يرجى كتابة شيء في مربع البحث',
        'back'    => 'العودة للرئيسية',
        'try_search'   => 'جرب البحث عن ولاية أخرى أو معلم سياحي مختلف.',
        'excu'   => 'عذراً، لم نجد أي نتائج..',
        'det_att'  => 'تفاصيل المعلم',
        'wilaya'   => 'ولاية',
        'serch_result'   => 'تم العثور على النتائج التالية في الولايات والمعالم السياحية',
        'result_s'  => 'نتائج البحث عن:',
        'gallery'   => 'معرض الصور',
        'about_att'  => 'عن المعلم',
        'exp_now'    => 'استكشف الآن',

        // --- Admin Dashboard Texts ---
        'admin_panel' => 'لوحة التحكم',
        'wilaya_mgmt' => 'إدارة الولايات',
        'attraction_mgmt' => 'إدارة المعالم',
        'restaurant_mgmt' => 'إدارة المطاعم',
        'hotel_mgmt' => 'إدارة الفنادق',
        'comments' => 'التعليقات',
        'welcome' => 'مرحباً',
        'restaurants' => 'المطاعم',
        'hotels' => 'الفنادق',
        'users' => 'المستخدمين',
        'quick_actions' => 'إجراءات سريعة',
        'add_wilaya' => 'إضافة ولاية',
        'add_attraction' => 'إضافة معلم',
        'add_restaurant' => 'إضافة مطعم',
        'add_hotel' => 'إضافة فندق',
        'view_site' => 'عرض الموقع',
        'tourism_mgmt' => 'إدارة السياحة',

        // --- Wilaya Table Columns (AR) ---
        'col_image' => 'الصورة',
        'col_name' => 'اسم الولاية',
        'col_coords' => 'الإحداثيات (خط الطول/العرض)',
        'col_desc' => 'الوصف',
        'col_actions' => 'العمليات',
        'confirm_delete' => 'هل أنت متأكد من الحذف؟',
        'col_att_name' => 'اسم المعلم',
        'col_wilaya' => 'الولاية',

        'col_rest_name' => 'اسم المطعم',
        'col_hotel_name' => 'اسم الفندق',
        'update_wilaya_title' => 'تحديث بيانات الولاية',
'select_wilaya' => 'اختر الولاية',
'desc_ar' => 'الوصف (بالعربية)',
'desc_en' => 'الوصف (بالإنجليزية)',
'upload_img' => 'رفع صورة',
'select_file' => 'اختر ملفاً من جهازك',
'latitude' => 'خط العرض (Lat)',
'longitude' => 'خط الطول (Lng)',
'btn_update' => 'تحديث وحفظ البيانات',
'success_update' => 'تم التحديث بنجاح!',

'add_attraction_title' => 'إضافة معلم سياحي جديد',
'name_ar' => 'الاسم (بالعربية)',
'name_en' => 'الاسم (بالإنجليزية)',
'col_category' => 'الفئة',
'img_multi_hint' => 'الصور (أول صورة ستكون العرض الرئيسي)',
'select_multi' => 'اختر عدة صور من جهازك',
'btn_save' => 'حفظ المعلم',
'success_add' => 'تمت الإضافة بنجاح!',
'main_label' => 'الرئيسية',

'add_restaurant_title' => 'إضافة مطعم جديد',
'rest_name_en' => 'اسم المطعم (بالإنجليزية)',
'rest_name_ar' => 'اسم المطعم (بالعربية)',
'rest_img' => 'صورة المطعم',
'click_select_img' => 'انقر لاختيار صورة',
'btn_save_rest' => 'حفظ المطعم',
'success_add_rest' => 'تم إضافة المطعم بنجاح!',

'add_hotel_title' => 'إضافة فندق جديد',
'hotel_name_en' => 'اسم الفندق (بالإنجليزية)',
'hotel_name_ar' => 'اسم الفندق (بالعربية)',
'hotel_img' => 'صورة الفندق',
'btn_save_hotel' => 'حفظ بيانات الفندق',
'success_add_hotel' => 'تم إضافة الفندق بنجاح!',

'edit_wilaya_header' => 'تعديل بيانات الولاية',
'wilaya_name_ar_label' => 'اسم الولاية (بالعربية)',
'desc_ar_label' => 'الوصف (بالعربية)',
'current_photo_label' => 'الصورة الحالية',
'change_photo_label' => 'تغيير الصورة (اختياري)',
'btn_save_all' => 'حفظ جميع التغييرات',

'edit_attraction_header' => 'تعديل تفاصيل المعلم',
'attraction_name_ar_label' => 'اسم المعلم (بالعربية)',
'desc_ar_label' => 'الوصف (بالعربية)',
'btn_update_attraction' => 'تحديث بيانات المعلم',

'edit_restaurant_title' => 'تعديل بيانات المطعم',
'restaurant_name_ar_label' => 'اسم المطعم (بالعربية)',
'btn_save_restaurant' => 'حفظ تغييرات المطعم',

'edit_hotel_title' => 'تعديل بيانات الفندق',
'hotel_name_ar_label' => 'اسم الفندق (بالعربية)',
'price_label' => 'سعر الليلة (د.ج)',
'btn_save_hotel' => 'حفظ تغييرات الفندق',
'btn_cancel'   => 'إلغاء',

'page_tit' => 'استكشف الولايات الجزائرية',
'exp_now' => 'استكشف الآن',
'map' => 'الخريطة التفاعلية',
'create_new_cc' => 'إنشاء حساب جديد؟',
'sure'     =>  ' ليس لديك حساب؟',
'btn_reset' => 'تراجع عن التعديلات',
'back_to_mgmt' => 'الرجوع لإدارة الولايات',
'col_lat' => 'خط العرض (Lat)',
'col_lng' => 'خط الطول (Lng)',
'back_to_mgmt_att' => 'الرجوع لإدارة المعالم',
'attraction_name_en_label' => 'اسم المعلم (EN)',
'desc_en_label' => 'الوصف (EN)',
// المفاتيح القديمة التي استخدمناها في صفحة الولاية سيعاد استخدامها تلقائياً
'back_to_mgmt_res' => 'الرجوع لإدارة المطاعم',

'btn_save_restaurant' => 'تحديث وحفظ البيانات',
'restaurant_name_ar_label' => 'اسم المطعم (AR)',
'back_to_mgmt_hotel' => 'العودة لإدارة الفنادق',

'back_to_mgmt_wilaya' => 'العودة لإدارة الولايات',
'btn_reset' => 'تراجع / إعادة تعيين',

'statistics_overview' => 'نظرة عامة على الإحصائيات',
'data_distribution' => 'توزيع البيانات',
'total_comments' => 'إجمالي التعليقات',

'latest_additions' => 'آخر الإضافات',
'top_content' => 'المحتوى الأكثر مشاهدة',
'attractions_by_type' => 'توزيع المعالم حسب النوع',
'wilayas_stats' => 'إحصائيات الولايات',
'museums' => 'متاحف',
'parks' => 'منتزهات',
'beaches' => 'شواطئ',
'historical' => 'مواقع تاريخية',

'top_liked' => 'الأكثر إعجاباً',
'completed_wilayas' => 'الولايات المكتملة',
'attractions_distribution' => 'توزيع المعالم على الولايات',

'statistics' => 'إحصائيات الموقع',
'categories_dist' => 'توزيع المعالم حسب التصنيف',
'wilaya_dist' => 'توزيع المعالم على الولايات',
'historical_cultural' => 'تاريخية وثقافية',
'nature' => 'طبيعة',
'desert' => 'صحراوية',
'beach' => 'ساحلية',

'top_commented' => 'أكثر المناطق تعليقاً',
'active_wilayas' => 'أكثر الولايات نشاطاً',
'add_hotel' => 'إضافة فندق',
'add_restaurant' => 'إضافة مطعم',


'ai_assistant' => 'المساعد الذكي',
'searching_location' => 'جاري تحديد موقعك...',
'nearby_places' => 'اكتشفنا موقعك!',
'location_success' => 'تم تحديد موقعك بنجاح. الخريطة ستوجهك الآن لأقرب المعالم.',
'location_denied' => 'يرجى السماح بالوصول للموقع لتفعيل الميزة الذكية',


'stats_title' => 'اكتشف روح الجزائر',
'stats_wilayas' => 'ولاية جزائرية يمكنك اكتشافها',
'stats_attractions' => 'معلم سياحي وتاريخي مسجل',
'stats_unesco' => 'مواقع مدرجة في قائمة اليونيسكو',



'ai_title' => 'المساعد الذكي',
'ai_welcome' => 'مرحبًا 👋 كيف يمكنني مساعدتك في اكتشاف الجزائر؟',
'ai_placeholder' => 'اكتب سؤالك هنا...',
'ai_default_reply' => '✨ يمكنني مساعدتك في اكتشاف أجمل الأماكن السياحية في الجزائر',
'ai_beach_reply' => '🏖️ أفضل الشواطئ: وهران، جيجل، بجاية',
'ai_desert_reply' => '🏜️ اكتشف جانت وتمنراست والصحراء الجزائرية',
'ai_history_reply' => '🏛️ قم بزيارة القصبة وتيمقاد والآثار الرومانية',
'ai_nature_reply' => '🌲 الجزائر تحتوي على جبال وغابات وشلالات رائعة',

'ai_suggest_title' => 'إليك بعض الاقتراحات:',
'ai_no_result' => 'عذراً، لم أجد معلومات دقيقة حول هذا الطلب، هل تقصد ولاية أخرى؟',
'ai_more_info' => 'اقرأ المزيد',


'review_title' => 'شاركنا رأيك حول الموقع',
'review_subtitle' => 'تقييمك يساعدنا على تطوير تجربة سياحية أفضل في الجزائر',
'improve_question' => 'ما الذي يمكننا تحسينه؟',
'suggest_design' => 'تحسين التصميم',
'suggest_places' => 'إضافة أماكن أكثر',
'suggest_ai' => 'تحسين الذكاء الاصطناعي',
'suggest_speed' => 'تحسين سرعة الموقع',
'suggest_translation' => 'تحسين الترجمة',
'suggest_hotels' => 'إضافة فنادق أكثر',
'write_suggestion' => 'اكتب اقتراحك الخاص...',
'send_review' => 'إرسال التقييم',
'login_to_review' => 'يجب تسجيل الدخول لتقييم الموقع',
'review_success' => 'شكراً ❤️ تم إرسال تقييمك بنجاح',


'site_ratings' => 'تقييمات الموقع',
'user_suggestions' => 'اقتراحات المستخدمين',
],

];
$flags = [
    'ar' => 'dz',
    'en' => 'us'
];
?>